version: '3.9'

services:
  postgres-anangular:
    restart: always
    image: postgres:16.2
    environment:
      POSTGRES_DB: dbAngular
      POSTGRES_USER: dbUser
      POSTGRES_PASSWORD: dbPassword
    ports:
      - "5434:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
      